services:
  netbox:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.netbox-http.rule=Host(`netboxtest.di.unimi.it`)
        - traefik.http.routers.netbox-http.entrypoints=http
        - traefik.http.routers.netbox-http.middlewares=https-redirect
        - traefik.http.routers.netbox-https.rule=Host(`netboxtest.di.unimi.it`)
        - traefik.http.routers.netbox-https.entrypoints=https
        - traefik.http.routers.netbox-https.tls=true
        - traefik.http.routers.netbox-https.tls.certresolver=le
        - traefik.http.services.netbox.loadbalancer.server.port=8080
        - traefik.http.middlewares.netbox-ipwhitelist.ipwhitelist.sourcerange=159.149.128.0/17
        - traefik.http.routers.netbox-https.middlewares=netbox-ipwhitelist
        
    networks:
        - traefik-public
        - netbox-network
networks:
    netbox-network:
        attachable: true
    traefik-public:
        external: true
